export const INPUT_QUIZ_TITLE = 'INPUT_QUIZ_TITLE';
export const INPUT_QUIZ_DATE = 'INPUT_QUIZ_DATE';
export const INPUT_QUIZ_SCORE = 'INPUT_QUIZ_SCORE';
export const SUBMIT_QUIZ = 'SUBMIT_QUIZ';
export const CHANGE_FORM = 'CHANGE_FORM';